server:
  port: 8800
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://40028-bk7.cdc.k8s:21101/bladex?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: root
    password: qVo33pJK0aiUx$wj
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8